### ISSUE TITLE
@ComputingForever

### ISSUE THREAD

**Issue by pirate486743186** [trizen/lbry-viewer#6]
I.... don't think that's a good default channel....

https://open.lbry.com/@ComputingForever:9/What%E2%80%99s-inside-the-Jabs--The-Truth-Continues-to-Emerge:7

**Comment by trizen** [comment]
Why? Because he questions the official narrative? We all should be questioning the official narrative and think with our own heads, rather than blindly obeying to whatever the government says.

Overall, ComputingForever is an excellent channel. Used to had 500K subscribers on YouTube before getting banned for questioning the masks and the lockdowns...
